name: Publish Artifact
on:
   push:
    branches:
      - master
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        run: ./gradlew build

      - name: Semantic Release Version
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check New Release Version
        run: echo "New release version is ${{ steps.semantic_release.outputs.new_release_version }}"

      - name: Publish artifact to GitHub Packages
        run: ./gradlew publish -Pversion=${{ steps.semantic_release.outputs.new_release_version }}
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




